### ISSUE TITLE
Add watch arguments field

### ISSUE THREAD

**Issue by vnvizitiu** [maartenba/DotNetWatch#10]
Hello,

I am using the plugin for a blazor application which has several launch profiles, for the dotnet watch one could use the **-lp, --launch-profile** flags but if I try to add them to the Programs arguments, they get added after the **--** which turns them into, as the field suggests, arguments for the child process that is being watched.

It would be helpful to have such a field to allow for more granular control of how dotnet-watch is being run, instead of adding more and more checkboxes or fields, it could be placed under an **advanced** grouping if you think it could confuse.

Or if this is a generic string builder sort of thing, one could even use **test** instead of running through such an approach.

I know it could be done via command-line but the usefulness of having it as a run/debug configuration in Rider is golden

Thank you

**Comment by maartenba** [comment]
That should work. Vacationing at the moment but will pick this up as one of the first things in 2024. Thanks for your suggestion!

**Comment by maartenba** [comment]
Update should be in the marketplace soon 👍

**Comment by vnvizitiu** [comment]
Been following the update on the marketplace intensely, just dropped in and it works great thank you 😄
