### ISSUE TITLE
Add checkbox to disable automatic browser launch

### ISSUE THREAD

**Issue by oal** [maartenba/DotNetWatch#5]
I see there's a checkbox for "Always restart on rude edit". It'd be nice to have something similar for disabling browser launch when starting dotnet watch.

DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER=1

See https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-watch

**Comment by maartenba** [comment]
Will be available in 2022.3 EAP soon 👍
