### ISSUE TITLE
regression for issue #2 Unable to use hotreload with --framework flag in command line enhancement

### ISSUE THREAD

**Issue by GiampaoloGabba** [maartenba/DotNetWatch#7]
As the title says, there is a regression for the issue #2.
The plugin started again to add the  --framework parameter, breaking the hotreload functionality.

I have a global.json specifing wich version i'm using, there is no need for the plugin to add the --framework parameter, breaking the hotreload.

Imho this parameter should be added as an optin, the default behaviour should be to not add it at all.

Thank you!

**Comment by GiampaoloGabba** [comment]
Some additional information: I have only one target framework available for this project, but the --framework parameter is still added.

![image](https://github.com/maartenba/DotNetWatch/assets/8319337/e8ade72e-8dc1-4567-b313-2eab8762e550)

**Comment by maartenba** [comment]
Can you share the command that was generated when you run the app?

Plus, do you have .net 8 preview on your machine?

**Comment by GiampaoloGabba** [comment]
The generated command is:
`"C:\Program Files\dotnet\dotnet.exe" watch run --project D:/Dati/Dropbox/Sviluppo/Web/TestTavoloUnito/WebUi/WebUi.csproj --framework net7.0`

and yes, i have installed VS2022 preview wich came with .net8 preview :( maybe this is the culprit?

**Comment by maartenba** [comment]
I believe it is. If you run this on the command line without the framework parameter, does that pick up net7.0 properly or does it run with net8.0?

**Comment by GiampaoloGabba** [comment]
I think that launching from the command line without the framework parameter picks up the .net7 version (or at least oh my poshj tells me that the .net version is 7.0.42):

![image](https://github.com/maartenba/DotNetWatch/assets/8319337/3e5fc731-f3f3-4dd9-abbc-5f98e30d5fdd)

If i use the --verbose flag i can see this:
![image](https://github.com/maartenba/DotNetWatch/assets/8319337/4d1ab64d-15a3-4a25-b82e-f0e5c84298df)

So i'm pretty sure is picking up the .net7 automatically (also i have a global.json for my solution like this:

`{
  "sdk": {
    "version": "7.0.0",
    "rollForward": "latestMajor",
    "allowPrerelease": false
  }
}`

**Comment by maartenba** [comment]
That checks out indeed. I'll see if I can omit the parameter altogether if there's only one TFM available in the project. Thanks for this suggestion/enhancement! Work in progress...

**Comment by maartenba** [comment]
An update was published to the marketplace and should be available in the next 24h.

**Comment by SaifAqqad** [comment]
It seems the new version is only compatible with 2023.3.x, which is currently in EAP.
is there any workaround to install it on 2023.2.x?

**Comment by GiampaoloGabba** [comment]
Ah! That’s why I wasn’t receiving the update. I’m not using the EAP 😢

**Comment by maartenba** [comment]
An update to teh stable version is pooushed to the marketplace, may take up to 24h to appear.
