### ISSUE TITLE
Program Argument --applicationpath keeps getting added

### ISSUE THREAD

**Issue by Asherslab** [maartenba/DotNetWatch#9]
Hi, 

have been attempting to get Hot Reload working with Blazor was using the botnet watch plugin, and I've just figured out the issue I've been having.

Long story short, within Program arguments a `--applicationpath <path-to-built-dll>` keeps being added into the run configuration after a single run. I can delete it once and it works, but then next run the argument is added back in and it no longer works.

specifically, with the above argument added I get the following error (with verbose on)
`Did not find a HotReloadProfile or running a non-default command. Watching with legacy behavior.`
without the argument, I get
`Project supports hot reload and was configured to run with the default run-command. Watching with hot-reload`
which is what I want.

deleting the run argument every time is quite tedious, so I'm wondering what might be done about this.
I looked in the repository a bit and didn't notice the plugin adding it itself, so I'm not 100% certain where it's coming from.

as a note I'm on MacOS, 
rider build: Build #RD-231.9161.46, built on June 22, 202
pluginversion: 2023.1.1

Thanks!

**Comment by maartenba** [comment]
`--applicationpath` is not added by the plugin, so am curious where this comes from.

@Asherslab could you send me a copy of your `.idea/workspace.xml` via maarten at jetbrains.com?

**Comment by Asherslab** [comment]
Hi @maartenba, I setup a dummy project to reproduce it with: 
https://github.com/Asherslab/dotnetwatch-testing

I've also produced a quick screen recording showing the behaviour. I also noticed that the applicationpath argument doesn't show in the workspace.xml


https://github.com/maartenba/DotNetWatch/assets/28527281/6d9e8874-10e1-406a-8b50-518945f84bff

**Comment by maartenba** [comment]
Found it - thank you for that repro project! It turns out the `--applicationpath` parameter is added by MSBuild/the project model. There are some [other reports](https://www.google.com/search?hl=nl&q=blazor%20output%20%2D%2Dapplicationpath) out there as well.

Stripping off the parameter now, expect an updated plugin version on the marketplace in the next few hours.
